### PR TITLE
[terra-toolkit] Upgraded css-loader to v3.2.0

### LINKED ISSUE #300: Evaluate css-loader v3 update
# Feature Request

## Description
css-loader v3 was just recently released. Need to evaluate it and see if we can update it in terra-toolkit as a passive update.

https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#300-2019-06-11

### PR DESCRIPTION
**Pull request by avinashg1994**
### Summary

Upgraded the version of "css-loader" from "^2.1.1" to "^3.2.0"

Resolves #300 

### Additional Details

Verified the update with Terra-Core, Terra-Framework, Terra-Clinical, Terra-Dev-Site and Terra-UI.

### CODE REVIEW

**Comment by StephenEsser** [comment]
How did you resolve the issues you were seeing here? Can you post a short explanation to what the issue was? 

https://github.com/cerner/terra-toolkit/issues/300#issuecomment-530374311

**Comment by avinashg1994** [comment]
> How did you resolve the issues you were seeing here? Can you post a short explanation to what the issue was?
> 
> [#300 (comment)](https://github.com/cerner/terra-toolkit/issues/300#issuecomment-530374311)

The issue mentioned [here](https://github.com/cerner/terra-toolkit/issues/300#issuecomment-530374311) is now resolved.
Initially, I had made changes only to the **"webpack.config.js"** with the updated syntax from css-loader where `localIdentName` had to be moved under the module object option. So when i tested these changes with "Terra-Dev-Site" i was getting a promise rejection warning followed by the error as seen in the comment (probably because dev-site is the only one with a theme file)
Later, after further analysis, I also updated **"getThemeWebpackPromise.js"** with the new syntax which then resolved the issue.
It was mainly a syntax mismatch which caused the error in dev-site.

**Review by bjankord — APPROVED** [review]

**Review by ShettyAkarsh — APPROVED** [review]

**Review by pranav300 — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
@avinashg1994 Can you open validation PRs in terra-dev-site and in terra-framework?

**Comment by avinashg1994** [comment]
> @avinashg1994 Can you open validation PRs in terra-dev-site and in terra-framework?

Validation PR links
Terra-Framework : https://github.com/cerner/terra-framework/pull/896
Terra-Dev-Site : https://github.com/cerner/terra-dev-site/pull/207

**Review by emilyrohrbough — APPROVED** [review]

**Review by lokesh-0813 — APPROVED** [review]

**Review by ryanthemanuel — APPROVED** [review]

**Pull request merged**
