### PR TITLE
Update waitForSeleniumHubReady to accommodate Windows users

### LINKED ISSUE #663: [terra-functional-testing] Invalid docker command for Windows
# Bug Report

## Description
The syntax in the `"docker inspect --format='{{json .State.Health.Status}}' selenium-hub"` [docker command](https://github.com/cerner/terra-toolkit/blob/cb967914cd9f14eeb54d7bf9c1847cc6592d366c/packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js#L104) is invalid when running in a Windows environment and causes a timeout when starting the Selenium Docker service. The single quote should be swapped with double quotes and vice versa according to the examples in the [docker documentation](https://docs.docker.com/engine/reference/run/#restart-policies---restart).

> SevereServiceError: Error: Timeout. Exceeded retry count for docker inspect --format='{{json .State.Health.Status}}' selenium-hub.

## Steps to Reproduce

1. Run `npm run test:wdio` in a Windows environment for a project that contains wdio tests.
2. The above timeout error occurs while starting the Selenium Docker Service.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by kaylabarnett**
Update poll command within waitForSeleniumHubReady to accommodate Windows users running WDIO tests

### Summary
Made an update to the poll command within waitForSeleniumHubReady to use single quotes. This change was made as using double quotes is causing parsing issues when the method is executed on Windows machines. This was found during development via one of our EPAM teams.

### Additional Details
Closes #663 

@cerner/terra

[CONTRIBUTORS.md]: ../blob/main/CONTRIBUTORS.md
[License]: ../blob/main/LICENSE

### CODE REVIEW

**Comment by mjhenkes** [comment]
@kaylabarnett thank you for the contribution!

Could you add yourself as a contributor here: https://github.com/kaylabarnett/terra-toolkit/blob/main/CONTRIBUTORS.md

**Review by benbcai — APPROVED** [review]

**Review by yuderekyu — APPROVED** [review]
@kaylabarnett thank you for the contribution! can we get someone with a windows machine to verify that this works?

**Review by mjhenkes — APPROVED** [review]

**Comment by benbcai** [comment]
> @kaylabarnett thank you for the contribution! can we get someone with a windows machine to verify that this works?

It's always good to have additional verification. Another Windows consumer ran into this issue recently but I had not heard back from them whether or not it resolved their issue. I just reached out and they confirmed that this change did resolve their issue so we can also use this as verification.

Screen Shot 2021-05-26 at 10 15 47 AM

Note: The `Chrome not reachable` error is a separate issue not related to this change.

**Comment by kaylabarnett** [comment]
> > @kaylabarnett thank you for the contribution! can we get someone with a windows machine to verify that this works?
> 
> It's always good to have additional verification. Another Windows consumer ran into this issue recently but I had not heard back from them whether or not it resolved their issue. I just reached out and they confirmed that this change did resolve their issue so we can also use this as verification.
> 
> Screen Shot 2021-05-26 at 10 15 47 AM
> 
> Note: The `Chrome not reachable` error is a separate issue not related to this change.

If we need additional verification I can reach out to my EPAM team to have them verify

**Comment by benbcai** [comment]
@kaylabarnett I think we're good as far as verification goes.

**Pull request merged**
