### PR TITLE
Attempt to fix the build

### PR DESCRIPTION
**Pull request by ryanthemanuel**
### Summary
There is some additional configuration that needs to take place to get jasmine working with es6.  I'm not sure why the PR build succeeded previously, but hoping this will work.

Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the [CONTRIBUTORS.md] file signifies agreement to all rights and reservations provided by the [License].

Thanks for contributing to Terra. 

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

**Comment by Matt-Butler** [comment]
I think the issue is with using import outside the `src` directory. Code is only transpiled in the `src` directory.
https://github.com/cerner/terra-toolkit/blob/master/package.json#L17

This statement below will not work outside the src directory:
```
import specReporter from 'jasmine-spec-reporter';
```

It must be rewritten like this:
```
const specReporter = require('jasmine-spec-reporter');
```

**Comment by ryanthemanuel** [comment]
jasmine-es6 should be able to take care of that: https://github.com/vinsonchuong/jasmine-es6

jasmine-es6 provides a jasmine executable, meant to be used in place of the executable provided by the jasmine package. It runs a project's Jasmine specs in a Babel environment, which transpiles ES6+ code at runtime.

**Comment by ryanthemanuel** [comment]
The problem was I hadn't configured it properly.

**Comment by Matt-Butler** [comment]
+1

**Pull request merged**
