### PR TITLE
[terra-functional-testing] Reorganize documentation on the dev site

### PR DESCRIPTION
**Pull request by StephenEsser**
### Summary

This PR reorganizes the terra-functional-testing documentation to appear under the developer tools section of the site.

Note:

This documentation will eventually be moved into terra-toolkit-docs, but because terra-toolkit-docs is a released package I kept the documentation inside of terra-functional-testing until the official release to prevent releasing documentation for unreleased packages.

Open to suggestions for the layout/organization/structure. Each service might have additional resources down the road. 

```
└── terra-functional-testing
    └── services
        ├── asset-server-service
        │   └── About.tool.mdx
        ├── selenium-docker-service
        │   └── About.tool.mdx
        ├── terra-service
        │   └── About.tool.mdx
        └── visual-regression-service
            └── About.tool.mdx
```

image

@cerner/terra

[CONTRIBUTORS.md]: ../blob/main/CONTRIBUTORS.md
[License]: ../blob/main/LICENSE

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
thoughts on changing services to wdio-services ?

**Review by emilyrohrbough — APPROVED** [review]

**Comment by mjhenkes** [comment]
Are we planning to add more content to each of the services? If not I'd drop the folder and just name the 'about' doc the name of the service to avoid drilling in to get the about doc.

**Comment by StephenEsser** [comment]
> Are we planning to add more content to each of the services? If not I'd drop the folder and just name the 'about' doc the name of the service to avoid drilling in to get the about doc.

I was thinking there might be more content added in the future so I left the door open, but I also don't know what that content would be. I'll flatten the structure a little bit. We can always update it later if we need it

Flattened to look as follows:

```
└── terra-functional-testing
    └── wdio-services
        ├── AssetServerService.tool.mdx
        ├── SeleniumDockerService.tool.mdx
        ├── TerraService.tool.mdx
        └── VisualRegressionService.tool.mdx
```

image

**Review by yuderekyu — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
Some of this doc, like configuration is good to have for ourselves, but I'm not sure we need to document it for our consumers since we want them to use the default config we provide. Example: https://terra-toolki-oraganize--lbgwnt.herokuapp.com/dev_tools/terra-functional-testing/terra-functional-testing/wdio-services/terra-service#configuration

Should we move the "config" docs to inline comments in the services themselves?

**Comment by StephenEsser** [comment]
My opinion is the the configuration should be documented as long as it's an API, if we don't want consumers being able to modify these values I think we should dissolve the API and configuration changes should be made directly in the service.

Alternatively we could avoid publishing these documents to the site, but have them available as needed

**Comment by mjhenkes** [comment]
I agree with @StephenEsser statement about documenting all APIs.

**Review by mjhenkes — APPROVED** [review]

**Comment by StephenEsser** [comment]
@emilyrohrbough I'm going to go ahead and merge this PR since it's just moving existing documentation around. If this is something you're interested in talking about more we can add it as a discussion topic in scrum or the WDIO sync

**Pull request merged**
